[2025-04-04T09:08:14.862+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-04-04T09:08:14.886+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-04-04T09:08:14.887+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:08:14.890+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T09:08:14.892+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:08:14.932+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_images> on 2024-01-01 00:00:00+00:00
[2025-04-04T09:08:14.950+0000] {standard_task_runner.py:55} INFO - Started process 2962 to run task
[2025-04-04T09:08:14.969+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'upload_images', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '735', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_collect.py', '--cfg-path', '/tmp/tmpnd0kqptt']
[2025-04-04T09:08:14.971+0000] {standard_task_runner.py:83} INFO - Job 735: Subtask upload_images
[2025-04-04T09:08:15.016+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T09:08:15.089+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T09:08:15.185+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.upload_images scheduled__2024-01-01T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T09:08:15.506+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=upload_images
AIRFLOW_CTX_EXECUTION_DATE=2024-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-01T00:00:00+00:00
[2025-04-04T09:08:15.537+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:08:15.539+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:08:15.541+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T09:08:17.366+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:08:17.368+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:08:18.542+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T09:08:18.648+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=upload_images, execution_date=20240101T000000, start_date=20250404T090814, end_date=20250404T090818
[2025-04-04T09:08:18.773+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T09:08:19.208+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
