[2025-04-04T08:59:38.911+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_images scheduled__2023-04-05T00:00:00+00:00 [queued]>
[2025-04-04T08:59:38.940+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_images scheduled__2023-04-05T00:00:00+00:00 [queued]>
[2025-04-04T08:59:38.940+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T08:59:38.962+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T08:59:38.964+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T08:59:39.106+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_images> on 2023-04-05 00:00:00+00:00
[2025-04-04T08:59:39.131+0000] {standard_task_runner.py:55} INFO - Started process 758 to run task
[2025-04-04T08:59:39.198+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_images', 'scheduled__2023-04-05T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/dagv2_data_collect.py', '--cfg-path', '/tmp/tmpln7jdl5k']
[2025-04-04T08:59:39.220+0000] {standard_task_runner.py:83} INFO - Job 186: Subtask download_images
[2025-04-04T08:59:39.311+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T08:59:39.464+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T08:59:39.788+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_images scheduled__2023-04-05T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T08:59:40.259+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_images
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-05T00:00:00+00:00
[2025-04-04T08:59:40.675+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T08:59:40.757+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=download_images, execution_date=20230405T000000, start_date=20250404T085938, end_date=20250404T085940
[2025-04-04T08:59:41.215+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T08:59:41.517+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
