[2025-04-04T09:00:11.541+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2025-04-04T09:00:11.623+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-04-20T00:00:00+00:00 [queued]>
[2025-04-04T09:00:11.625+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:00:11.627+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T09:00:11.628+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:00:11.706+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_images> on 2023-04-20 00:00:00+00:00
[2025-04-04T09:00:11.750+0000] {standard_task_runner.py:55} INFO - Started process 916 to run task
[2025-04-04T09:00:11.786+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'upload_images', 'scheduled__2023-04-20T00:00:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/dagv2_data_collect.py', '--cfg-path', '/tmp/tmpg3oof3a7']
[2025-04-04T09:00:11.793+0000] {standard_task_runner.py:83} INFO - Job 224: Subtask upload_images
[2025-04-04T09:00:11.855+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T09:00:11.932+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T09:00:12.051+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.upload_images scheduled__2023-04-20T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T09:00:12.680+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=upload_images
AIRFLOW_CTX_EXECUTION_DATE=2023-04-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-20T00:00:00+00:00
[2025-04-04T09:00:12.781+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:00:12.796+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:00:12.807+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T09:00:16.496+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:00:16.507+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:00:17.902+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T09:00:17.960+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=upload_images, execution_date=20230420T000000, start_date=20250404T090011, end_date=20250404T090017
[2025-04-04T09:00:18.041+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T09:00:18.091+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
