[2025-04-04T09:07:06.306+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2025-04-04T09:07:06.428+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.upload_images scheduled__2023-11-29T00:00:00+00:00 [queued]>
[2025-04-04T09:07:06.443+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:07:06.446+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T09:07:06.447+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:07:06.607+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): upload_images> on 2023-11-29 00:00:00+00:00
[2025-04-04T09:07:06.617+0000] {standard_task_runner.py:55} INFO - Started process 2705 to run task
[2025-04-04T09:07:06.635+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'upload_images', 'scheduled__2023-11-29T00:00:00+00:00', '--job-id', '672', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_collect.py', '--cfg-path', '/tmp/tmpz8yzguic']
[2025-04-04T09:07:06.637+0000] {standard_task_runner.py:83} INFO - Job 672: Subtask upload_images
[2025-04-04T09:07:06.682+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T09:07:06.756+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T09:07:06.906+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.upload_images scheduled__2023-11-29T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T09:07:07.281+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=upload_images
AIRFLOW_CTX_EXECUTION_DATE=2023-11-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-29T00:00:00+00:00
[2025-04-04T09:07:07.342+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:07:07.346+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:07:07.348+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T09:07:11.218+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:07:11.220+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:07:13.660+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T09:07:13.736+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=upload_images, execution_date=20231129T000000, start_date=20250404T090706, end_date=20250404T090713
[2025-04-04T09:07:13.854+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T09:07:13.958+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
